name: musilm_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_inset_box_shadow: ^1.0.8
  flutter_qiblah: ^2.1.0
  flutter_screenutil: ^5.5.4
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.5
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  get_it: ^7.2.0
  hijri: ^3.0.0
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  # lottie: ^1.1.0
  motion_sensors: ^0.1.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: assets/images/splash_screen.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/praytime/
    - assets/images/praytime_slider/
    - assets/localdb/azkar.json
    - assets/localdb/azkar1.json
    - assets/localdb/azkar2.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-semiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    - family: Scheherazade New
      fonts:
        - asset: assets/fonts/Schehera-Bold.ttf
          weight: 700
        - asset: assets/fonts/Schehera-Regular.ttf
          weight: 400
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/categories_icons.ttf
        - asset: assets/fonts/surah_number_icon.ttf
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
